config/routes.rb
Rails.application.routes.draw do

  root 'bookings#index'

  devise_for :users, :controllers => { registrations: 'registrations' }

    resources :bookings, :only => [:index, :new, :create] do
      collection do
        get 'upcoming'
        get 'todays'
      end
    end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  validates :starts_at, :ends_at, presence: true
  validate :check_for_room_availability, :on => :create
  belongs_to :user
  belongs_to :meeting_room

  def check_for_room_availability
    if Booking.exists?(["starts_at < ? AND ends_at > ? AND meeting_room_id = ? ",self.ends_at,self.starts_at,self.meeting_room_id])
      errors.add(:base, "Selected meeting room is not available for the given time interval. Please choose a different location or time!")
    end
  end

  def booked_room
    MeetingRoom.where(id: self.meeting_room_id)
  end

  def invitee_names
    invitee_ids = self.invitees
    User.where(id: invitee_ids).select("name").map(&:name).join(',')
  end
end

app/models/meeting_room.rb
class MeetingRoom < ActiveRecord::Base
  validates :name, :location,  presence: true
  has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

   validates :name,  presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_user_time_zone

  def set_user_time_zone
     Time.zone = current_user.timezone if user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :authenticate_user!
  before_action :new,  only: [:index, :upcoming, :todays]

  def index
    @booked_room_list = Booking.where(status: false).order("starts_at DESC").last(100)
  end

  def new
    @book_room = Booking.new
    @meeting_rooms_lists = MeetingRoom.all
  end

  def create
    @book_room = Booking.new(booking_params)
    if @book_room.save
      flash[:success] = "Meeting room is successfully booked for you!!"
    else
      flash[:errors] = @book_room.errors.full_messages.to_sentence
    end
    redirect_to root_path
  end

  def upcoming
    @booked_room_list = Booking.where("starts_at >= ?" ,DateTime.current).order(:starts_at)
    render :index
  end

  def todays
    @booked_room_list = Booking
      .where("starts_at >= ? AND starts_at <= ?", Time.current.beginning_of_day,Time.current.end_of_day)
      .order(:starts_at)
    render :index
  end

  private

  def booking_params
    params.require(:booking)
      .permit(:meeting_room_id,:starts_at,:ends_at, :agenda, :invitees => [])
      .merge( user_id: current_user.id,status: false)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmatiion, :timezone)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmatiion, :timezone)
  end

   def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_action(action)
    controller_action = "#{controller.controller_name}/#{controller.action_name}"
    return 'default' if controller_action == action
    return 'danger'
  end

  def row_class(room)
    return "success" if room.starts_at.to_date.today?
    return "warning" if room.starts_at.to_date.future?
  end
end

app/views/bookings/home.html.erb
<div class=" page-header header-all-page ">
  <h2>BookandGo <small>We make it easy..</small></h2>
</div>
    <div id="myCarousel" class="carousel slide" style="width: 800px; margin: 0 auto" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("sample9.jpg") %>
      <div class="carousel-caption">
         <h2>BookandGo</h2>

        <h4><p>Booking Meetings Rooms have Never Been This Easy Before.Online application to book meeting rooms.Book your meeting room in a single click..</p></h4>
        <p>
          <a class="btn btn-lg btn-primary" href="<%= new_booking_path%>" role="button"><span class = "glyphicon glyphicon-tags"></span> Click Here to Book...</a>
        </p>
      </div>
    </div>

    <div class="item">
     <%= image_tag("sample2.jpg") %>
      <div class="carousel-caption">
         <h2>BookandGo</h2>
        <h4><p>Booking Meetings Rooms have Never Been This Easy Before.Online application to book meeting rooms.Book your meeting room in a single click..</p></h4>
        <p>
          <a class="btn btn-lg btn-primary" href="<%= new_booking_path%>" role="button"><span class = "glyphicon glyphicon-tags"></span> Click Here to Book...</a>
        </p>
      </div>
    </div>

    <div class="item">
      <%= image_tag("sample7.jpg") %>
      <div class="carousel-caption">
         <h2>BookandGo</h2>
        <h4><p>Booking Meetings Rooms have Never Been This Easy Before.Online application to book meeting rooms.Book your meeting room in a single click..</p></h4>
        <p>
          <a class="btn btn-lg btn-primary" href="<%= new_booking_path%>" role="button"><span class = "glyphicon glyphicon-tags"></span> Click Here to Book...</a>
        </p>
      </div>
    </div>

    <div class="item">
      <%= image_tag("sample9.jpg") %>
<div class="carousel-caption">
         <h2>BookandGo</h2>

        <h4><p>Booking Meetings Rooms have Never Been This Easy Before.Online application to book meeting rooms.Book your meeting room in a single click..</p></h4>
        <p>
          <a class="btn btn-lg btn-primary" href="<%= new_booking_path%>" role="button"><span class = "glyphicon glyphicon-tags"></span> Click Here to Book...</a>
        </p>
      </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/bookings/index.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="btn-group">
      <%= link_to "All", bookings_path, :class => "btn btn-#{active_action('bookings/index')}" %>
      <%= link_to "Today", todays_bookings_path, :class => "btn btn-#{active_action('bookings/todays')}" %>
      <%= link_to "Upcoming", upcoming_bookings_path, :class => "btn btn-#{active_action('bookings/upcoming')}" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <%if @booked_room_list.present? %>
      <table class="table table-bordered table-hover display" id=
      "upcoming_table">
        <thead>
          <tr style="background-color: #EEE;">
            <th>Meeting Room</th>
            <th>Booked By</th>
            <th>From</th>
            <th>To</th>
          </tr>
        </thead>
        <tbody>
          <%@booked_room_list.each do |room|%>
          <tr class="<%= row_class(room) %>">
            <td><%=room.meeting_room.name%></td>
            <td><%=room.user.name%></td>
            <td style="font-weight: bold">
            <%=room.starts_at.strftime("%d/%m/%Y at %H:%M %p")%></td>
            <td style="font-weight: bold">
            <%=room.ends_at.strftime("%d/%m/%Y at %H:%M %p")%></td>
          </tr><%end%>
        </tbody>
      </table><%else%>
      <div class="border-width">
        <div style="text-align: center">
          <h2>No Bookings to display</h2>
        </div>
      </div><%end%>
    </div>
    <div class="col-md-4 foo book">
      <h1><span class="glyphicon glyphicon-hand-right"></span> &nbsp;Book
      your Room</h1>
      <div>
        <%if flash[:errors] %>
        <div class="alert alert-danger fade in fade_alerts">
          <strong></strong><%=flash[:errors]%>.
        </div><%end %><%if flash[:success].present?%>
        <div class="alert alert-success fade in fade_alerts">
          <strong>Success!</strong> <%=flash[:success]%>.
        </div><%end%>
      </div><%= form_for @book_room do |f| %>
      <div>
        <%= f.select :meeting_room_id, options_for_select(@meeting_rooms_lists.collect { |room| [room.name.titleize, room.id] }, 1), {}, { id: 'rooms_select' ,:class => "form-control mrg-top"} %>
      </div>
      <div class="row-padding">
        <%= f.text_field :starts_at, :required => true, :id => 'datetimepicker_start', :placeholder => "Start's at",:class => "form-control mrg-top"%>
      </div>
      <div class="row-padding">
        <%= f.text_field :ends_at, :required => true, :id => 'datetimepicker_end',:placeholder => "End's at", :class => "form-control mrg-top"%>
      </div>
      <div class="row-padding">
        <%= f.text_area :agenda, :required => true, :placeholder => "Agenda (Optional)", :class => "form-control mrg-top", :rows => "3"%>
      </div>
      <div class="row-padding mrg-btm">
        <%=f.submit 'Book The Room', :id => "book_room", :class => ["btn", "btn-danger", "mrg-top"] , data: {disable_with: "Checking Availabilty.."}%>
      </div><%end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="page-header header-all-page">
  <h2>Book your Room <small>A Click away to book</small></h2>
</div>

<div class=" col-md-12 col-sm-12 col-lg-12">
  <%if @book_room.errors.any? %>
    <div class="danger">
      <h2><%= pluralize(@book_room.errors.count, "error") %></h2>
      <ul>
        <%@book_room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li><%end %>
      </ul>
    </div><%end %><%if flash[:success].present?%>
    <div class="alert alert-success fade in fade_alerts">
      <strong>Success!</strong> <%=flash[:success]%>.
    </div>
  <%end%>
</div>

<div class="container-fluid">
  <%= form_for @book_room do |f| %>
    <div class="row row-padding">
      <div class="col-md-3 col-sm-6 col-lg-3 col-xs-4">
        <label class="control-label" for="fromtime">Select Meeting
        Room:</label>
      </div>
      <div class="col-md-4 col-sm-8 col-lg-4 col-xs-10">
        <%= f.select :meeting_room_id, options_for_select(@meeting_rooms_lists.collect { |room| [room.name.titleize, room.id] }, 1), {}, { id: 'rooms_select' ,:class => "form-control"} %>
      </div>
    </div>
    <div class="row row-padding">
      <div class="col-md-3 col-sm-6 col-lg-3 col-xs-8">
        <label class="control-label" for="fromtime">From:</label>
      </div>
      <div class="col-md-4 col-sm-8 col-lg-4 col-xs-10">
        <%= f.text_field :starts_at, :required => true, :id => 'datetimepicker_start', :class => "form-control"%>
      </div>
    </div>
    <div class="row row-padding">
      <div class="col-md-3 col-sm-6 col-lg-3 col-xs-8">
        <label class="control-label" for="fromtime">To:</label>
      </div>
      <div class="col-md-4 col-sm-8 col-lg-4 col-xs-10">
        <%= f.text_field :ends_at, :required => true, :id => 'datetimepicker_end', :class => "form-control"%>
      </div>
    </div>
    <div class="row row-padding">
      <div class="col-md-3 col-sm-6 col-lg-3 col-xs-8">
        <label class="control-label" for="fromtime">Attendees:</label>
      </div>
      <div class="col-md-4 col-sm-8 col-lg-4 col-xs-10">
        <%= f.select :invitees, options_for_select(@employees_list.collect { |user| [user.name.titleize, user.id] }, 1), {}, { multiple: true ,id: 'users_select' ,:class => "form-control"} %>
      </div>
    </div>
    <div class="row row-padding">
      <div class="col-md-3 col-sm-6 col-lg-3 col-xs-8">
        <label class="control-label" for="fromtime">Subject:</label>
      </div>
      <div class="col-md-4 col-sm-8 col-lg-4 col-xs-10">
        <%= f.text_area :agenda, :class => "form-control", :rows => "3"%>
      </div>
    </div>
    <div class="row row-padding">
      <div class="col-md-3 col-sm-6 col-lg-3 col-xs-8"></div>
      <div class="col-md-4 col-sm-8 col-lg-4 col-xs-10">
        <%=f.submit 'Book The Room', :id => "book_room", :class => ["btn", "btn-info"] , data: {disable_with: "Checking Availabilty.."}%>
      </div>
    </div>
  <%end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BookandGo</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class = "navbar-brand" href="<%=root_path%>">BookandGo</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class = "navbar-text">
              Logged in as <%= current_user.name %>.
             </li>
             <li>
              <%= link_to "Logout" , destroy_user_session_path, method: :delete%>
            </li>
          <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class = "container container-margin-top">
    <!-- Page Content -->
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade_alerts" role="alert"><%= notice %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    <%end%>
    <%if alert %>
      <div class="alert alert-danger alert-dismissible fade_alerts" role="alert"><%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    <% end %>
    <%= yield %>

  </div>

  <!-- Menu Toggle Script -->
  <script type="text/javascript">
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
        $("#reverse-class").toggleClass("glyphicon glyphicon-arrow-left glyphicon glyphicon-arrow-right");
    });
  </script>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BookandGo</title>

  <!-- Custom CSS -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
    body {
        padding-top: 80px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top.
         Change if height of navigation changes. */
    }
  </style>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body class = "bg-image">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class = "navbar-brand" href="<%=root_path%>">BookandGo</a>
        </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Login', new_user_session_path %></li>
        </ul>
      </div>
    </div>
  </nav>

    <!-- Page Content -->
  <div class="container">
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade_alerts" role="alert"><%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    <%end%>
    <%if alert %>
      <div class="alert alert-danger alert-dismissible fade_alerts" role="alert"><%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>